Shared/Message.cs
Shared/Shared.csproj

Added two private helper methods to convert an image to a base64 string and back.
Also added the property image to the message class.

Image to base64 functionality

---

Shared/Message.cs
Shared/Shared.csproj

Message:
- chg: Readability, minor documentation improvements.
- rmv: Unneeded hardcoded reference from project file.

Remove hardcoded paths, minor doc improvements

---

Client/Models/Group.cs
Server/CommunicationHandler.cs
Shared/JsonMessage.cs
Shared/Message.cs

Message:
- impl: MessageType enum which represents all message types as of the
current protocol.
CommunicationHandler:
- refac: if-else replaced with switch case which checks for MessageType.
Client/Group.cs:
- chg: Demonstrated use of MessageType when creating a message.

Added MessageType enum

---

Client/Models/Group.cs
Server/Client.cs
Server/CommunicationHandler.cs
Server/Connection.cs
Server/Group.cs
Server/Server.cs
Shared/Connection.cs

Shared/Connection.cs:
- impl: Shared connection class with writing functionality
Server/Server.cs:
- add: Added dictionary which keeps track of the clients and their
related connections. Also added methods to retrieve/add a client or a
connection.
Server/Client.cs:
- chg: Client now represents database data only.
Server/Group.cs:
- chg: For each message to send to the group, the corresponding
connection is now first retrieved before sending the message.

Added shared Connection, implemented dictionary.

---

Server/CommunicationHandler.cs
Server/Connection.cs
Server/Server.cs

- refac: Added all messagetypes to the switch and added placeholder
methods/implementation (since not a lot is possible without a database).
- chg: Class is now static, should improve performance.
Server/Server:
- impl: Ability to remove a connection from an associated client.
- add: Log when removing a connection from a client.
Server/Connection:
- add: Remove client when exception is thrown during reading. Log
exception type instead of whole message.

Placeholder-implement register/login requests

---

Client/Models/Client.cs
Client/Models/Group.cs
Shared/Message.cs

- add: implementation of export csv string for all messages in client

implemented csv export of all messages on client side

---

Server/CommunicationHandler.cs
Server/Connection.cs
Shared/Connection.cs

Shared/Connection:
- chg: SendData is now virtual, so children can overwrite it and use
their own exception handling strategy but still use the base method.
Server/Connection:
- impl: "Log the client out" by removing the client / connection
association upon an exception while reading.
- impl: Close the connection upon a signout message.

Close the connection upon disconnect or signout.

---

Shared/Helper.cs
Shared/Json/JsonMessage.cs
Shared/Json/JsonMessageClient.cs
Shared/Json/JsonMessagePayload.cs
Shared/LoginStruct.cs
Shared/Message.cs
Shared/RegisterStruct.cs

Message:
- chg: Moved image helper functions to separate helper class. Clientname
is also encoded/decoded in base64.
- impl: Easily set login and register info using structures, which are
encoded and decoded using properties.
Helper:
- add: Helper class to group helper functions together, to convert
strings to base64 and back, same with images.
Login/RegisterStruct:
- add: Structures to easily set login/register info.
JsonMessage:
- refac: Moved JsonMessage*-classes to own namespace to reduce clutter.

Added login.register structures and helper class.

---

Client/Models/CommunicationHandler.cs
Client/Models/Group.cs
Client/Views/MainPage.xaml.cs
Server/CommunicationHandler.cs
Server/Group.cs
Server/Server.cs
Shared/Group.cs
Shared/Message.cs

Shared:
- add: Shared Group class to use as a base class for the client and
server group classes.
- impl: It is now possible to set and get a list of groups from the
message, which are encoded/decoded to/from base64 in the payloaddata.
- impl: Respond to grouplist requests.
Client/CommunicationHandler:
- impl: Handle grouplist responses.
Server/Server:
- add: Getter for the group list. Ideally, this will be replaced by a
proper database handler soon.

Implemented RequestGroups, added shared group.

---

Server/Client.cs
Server/CommunicationHandler.cs
Server/DatabaseHandler.cs
Server/Group.cs
Server/Server.cs
Server/Server.csproj

**First database implementation:**
- add: DatabaseHandler
**Client:**
- add: Email property.
- rmv: Constructor with parameters.
**CommunicationHandler:**
- chg: the call to the client constructor.
**DatabaseHandler:**
- add: CreateDatabase(), CreateMessageTable(), CreateGroupParticipantsTable(), CreateGroupTable(), CreateUserTable()
AddClient, AddGroup, AddClientToGroup, GetGroups(), GetClients(), GetGroupParticipants().
**Group:**
- chg: Before sending a message to the client, check if the connection is not equal to null.
**Server:**
- chg: in main, do a call to create database. This method will check if the database file was already created. If not, it will create the database.
- chg: in the constructor of the server -> do a call to the databasehandler to get the groups and the …

Database implementation

---

Server/CommunicationHandler.cs
Server/Group.cs
Server/Server.cs

- impl: Unsuccessful response. Implemented join/leave group. Added group
list upon logging in.
Server/Server:
- fix: Check for null for various operations.

Restructured login/register,

---

Server/DatabaseHandler.cs

Server/DatabaseHandler:
- fix: Build issue where the name and id of a new group were the wrong
way around for the group constructor. They have been switched.

Fix build issue w.r.t. group creation.

---

Server/CommunicationHandler.cs
Server/DatabaseHandler.cs
Server/Group.cs
Server/Helper.cs
Server/Server.cs

added databse call to different message handling routes

Added databasecalls

---

Client/Models/CommunicationHandler.cs
Client/Models/Group.cs
Server/CommunicationHandler.cs

communicationhandler gemaakt. Voor iedere messagetype een method aangemaakt. Wanneer er een nieuwe groep word aangemaakt deze toegevoegd aan de groups list in de Client. bij de chatmessage deze toegevoegd aan de list in de desbetreffende group.

Client protocol implementatie

---

Server/CommunicationHandler.cs
Server/DatabaseHandler.cs
Server/Group.cs
Server/Server.cs

- add: todo for database handler in chatmessage.
General:
- fix: documentation.

Added todo in HandleChatmessage.

---

Server/CommunicationHandler.cs

Finally, both groupname and ID are sent from the server upon create/join group request.
The RegisterGroupResponse method has been refactored to do even less work when the sent client ID is invalid. Comments have been added.
Rebased on master so no merge conflicts should occur.

Groupname response

---

Shared/Message.cs

Shared/Message:
- fix: Nullreference in PayloadData when PayloadType was not set.

Fix nullreference in PayloadData.

---

Client/Models/CommunicationHandler.cs
Server/CommunicationHandler.cs
Server/Connection.cs
Shared/Message.cs

Server/Connection:
- impl: Server sends keepalive message to client every interval. If no
response has been received, Close() connection. ReadData() and
SendData() also call close upon exception, besides checking if
connection has already been closed.
- impl: Invoke event when keepalive message received from client.
Client/Models/CommunicationHandler:
- impl: Respond to the server sending keepalive messages by sending them
back.
Shared/Message:
- add: keepalive messagetype.

Poll client with keepalive messages.

---

Client/Models/CommunicationHandler.cs
Client/ViewModels/AddGroupPageViewModel.cs
Client/ViewModels/LoginPageViewModel.cs
Client/ViewModels/MainPageViewModel.cs
Client/ViewModels/SignUpPageViewModel.cs
Client/Views/AddGroupPage.xaml
Client/Views/LoginPage.xaml
Client/Views/MainPage.xaml
Client/Views/SignUpPage.xaml

added errormessages to login, creategroup en signup.
added export button

Msg error export

---

Server/CommunicationHandler.cs
Server/DatabaseHandler.cs

Messages will be added to the database now. Also fixed typo: Messsage -> Message.

add message to databse

---

Client/Models/Client.cs
Client/Models/CommunicationHandler.cs
Client/Models/Group.cs
Client/ViewModels/MainPageViewModel.cs

Client/Models/CommunicationHandler:
- fix: Clientname was not set after login.
Client/Models/Client:
- refac: Renamed Clientname => Name, just like Id.

Set clientname after succesfull login.

---

Client/Models/Client.cs
Client/Models/CommunicationHandler.cs
Client/Models/Connection.cs
Client/Models/Group.cs
Client/ViewModels/LoginPageViewModel.cs
Client/ViewModels/SignUpPageViewModel.cs
Server/Connection.cs
Server/Server.cs
Shared/Connection.cs

Connection is now opened after login or registering. When the server disappears unexpectedly, an event is raised and the connection is closed.

Open connection on login/register, properly close socket.

---

Server/Configuration.cs
Server/Server.cs

Server:
- rmv: private readonly port;
- add: GetPort() function which gets the port from the config.
- chg: writeline now also informs about the listening port.
Configuration:
- add: writeline for new config.
- add: writer.Flush()

Added server port configurable functionallity

---

Client/App.xaml.cs
Client/Models/Client.cs
Client/Models/CommunicationHandler.cs
Client/Models/Helper.cs
Client/Services/Converters/Base64ToImageConverter.cs
Client/ViewModels/AddGroupPageViewModel.cs
Client/ViewModels/JoinGroupPageViewModel.cs
Client/ViewModels/LoginPageViewModel.cs
Client/ViewModels/SignUpPageViewModel.cs

Helper:
- add: RunOnUI and RunOnUIAsync methods, to enable awaiting. Not without
a catch which is documented.
ViewModels:
- refac: Renamed eventargs from "Groups" to "e" as per convention.

Added UI Helper methods (#72).

---

Client/ResourceDictionaryClient.xaml
Client/ViewModels/AddGroupPageViewModel.cs
Client/ViewModels/JoinGroupPageViewModel.cs
Client/ViewModels/MainPageViewModel.cs
Client/ViewModels/SettingsPageViewModel.cs
Client/Views/AddGroupPage.xaml
Client/Views/JoinGroupPage.xaml
Client/Views/LoginPage.xaml
Client/Views/MainPage.xaml
Client/Views/SettingsPage.xaml

Menubars same style on each page.
Backbutton settingspage, prevents going back to login page when logged in.
Moved some styles to the dictionary

Multiple changes, see desc

---

Client/ViewModels/JoinGroupPageViewModel.cs
Client/Views/JoinGroupPage.xaml
Client/Views/SettingsPage.xaml

Extra textblocks op de settingspage
Message als er geen groups zijn om te joinen,
Bug dat listview verspringt opgelost

Settingspage listview fix

---

Client/ResourceDictionaryClient.xaml
Client/ViewModels/LoginPageViewModel.cs
Client/ViewModels/MainPageViewModel.cs

added comments to the login- en main- viewmodel.
de terug knop op de settings pagina van kleur en lettertype veranderd zodat deze consistent is met de andere knoppen in het programma

Comments login en main viewmodel

---

Client/Models/CommunicationHandler.cs
Client/Models/Group.cs
Client/Models/Helper.cs
Client/Services/Converters/Base64ToImageConverter.cs
Client/Services/Converters/DateTimeToTimeConverter.cs
Client/Services/Utilities/ImageUtilityService.cs
Client/Services/Utilities/MessageDataTemplateSelector.cs
Server/DatabaseHandler.cs

- add comments
- replaces dispacther logic into addMessage.

update add comments

---

Client/Models/Client.cs
Shared/Helper.cs

removal of usings

---

Client/ViewModels/AddGroupPageViewModel.cs
Client/ViewModels/JoinGroupPageViewModel.cs
Client/ViewModels/MainPageViewModel.cs

In viewmodels call the Client.Instance.Logout in stead of implementing this logic in each viewmodel

fix after logout groups duplicated issue
